conda_build_tool: rattler-build
provider:
  linux_aarch64: default
build_platform:
  linux_aarch64: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  version_updates:
    allowed_tag_globs: 'nccl4py-v*'
    sources:
      - github
